In [1]:
import numpy as np
import pandas as pd

In [4]:
df=pd.read_csv("/Users/pradeepprkakash/Downloads/dirty_cafe_sales.csv")

In [9]:
df

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,UNKNOWN,2023-08-30
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [10]:
df["Location"].unique()

<StringArray>
['Takeaway', 'In-store', 'UNKNOWN', nan, 'ERROR']
Length: 5, dtype: str

In [14]:
df["Location"]=df["Location"].replace("UNKNOWN",pd.NA)

In [15]:
df

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,NaN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,NaN,2023-08-30
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [16]:
df["Location"].unique()

<StringArray>
['Takeaway', 'In-store', nan, 'ERROR']
Length: 4, dtype: str

In [17]:
df["Location"]=df["Location"].replace("ERROR",pd.NA)

In [18]:
df

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,NaN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,NaN,2023-08-30
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [19]:
df.head(50)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,NaN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
5,TXN_2602893,Smoothie,5,4.0,20.0,Credit Card,NaN,2023-03-31
6,TXN_4433211,UNKNOWN,3,3.0,9.0,ERROR,Takeaway,2023-10-06
7,TXN_6699534,Sandwich,4,4.0,16.0,Cash,NaN,2023-10-28
8,TXN_4717867,NaN,5,3.0,15.0,NaN,Takeaway,2023-07-28
9,TXN_2064365,Sandwich,5,4.0,20.0,NaN,In-store,2023-12-31
10,TXN_2548360,Salad,5,5.0,25.0,Cash,Takeaway,2023-11-07
11,TXN_3051279,Sandwich,2,4.0,8.0,Credit Card,Takeaway,ERROR
12,TXN_7619095,Sandwich,2,4.0,8.0,Cash,In-store,2023-05-03
13,TXN_9437049,Cookie,5,1.0,5.0,NaN,Takeaway,2023-06-01
14,TXN_8915701,ERROR,2,1.5,3.0,NaN,In-store,2023-03-21
15,TXN_2847255,Salad,3,5.0,15.0,Credit Card,In-store,2023-11-15
16,TXN_3765707,Sandwich,1,4.0,4.0,NaN,NaN,2023-06-10
17,TXN_6769710,Juice,2,3.0,6.0,Cash,In-store,2023-02-24
18,TXN_8876618,Cake,5,3.0,15.0,Cash,NaN,2023-03-25
19,TXN_3709394,Juice,4,3.0,12.0,Cash,Takeaway,2023-01-15
20,TXN_3522028,Smoothie,ERROR,4.0,20.0,Cash,In-store,2023-04-04
21,TXN_3567645,Smoothie,4,4.0,16.0,Credit Card,Takeaway,2023-03-30
22,TXN_5132361,Sandwich,3,4.0,12.0,Digital Wallet,Takeaway,2023-12-01
23,TXN_2616390,Sandwich,2,4.0,8.0,NaN,NaN,2023-09-18
24,TXN_9400181,Sandwich,5,4.0,20.0,Cash,In-store,2023-06-03
25,TXN_7958992,Smoothie,3,4.0,NaN,UNKNOWN,NaN,2023-12-13
26,TXN_5183041,Cookie,5,1.0,5.0,Credit Card,In-store,2023-04-20
27,TXN_5695074,Juice,4,3.0,12.0,Credit Card,Takeaway,2023-04-10
28,TXN_8467949,Smoothie,5,4.0,20.0,Credit Card,NaN,2023-03-11
29,TXN_7640952,Cake,4,3.0,12.0,Digital Wallet,Takeaway,ERROR
30,TXN_1736287,NaN,5,2.0,10.0,Digital Wallet,NaN,2023-06-02
31,TXN_8927252,UNKNOWN,2,1.0,ERROR,Credit Card,NaN,2023-11-06
32,TXN_9677376,Smoothie,4,4.0,16.0,NaN,In-store,2023-08-15
33,TXN_7710508,UNKNOWN,5,1.0,5.0,Cash,NaN,ERROR
34,TXN_8853997,Smoothie,2,4.0,8.0,Digital Wallet,Takeaway,2023-10-09
35,TXN_9130559,Sandwich,1,4.0,4.0,Credit Card,NaN,2023-05-28
36,TXN_6855453,UNKNOWN,4,3.0,12.0,NaN,In-store,2023-07-17
37,TXN_1080432,Salad,2,5.0,10.0,Credit Card,In-store,2023-04-29
38,TXN_2655815,Smoothie,4,4.0,16.0,NaN,Takeaway,2023-06-08
39,TXN_6688524,Coffee,4,2.0,8.0,ERROR,NaN,2023-06-29
40,TXN_2083138,Smoothie,3,4.0,12.0,NaN,In-store,2023-04-17
41,TXN_2427584,Sandwich,4,4.0,16.0,NaN,Takeaway,2023-12-22
42,TXN_6650263,Tea,2,1.5,UNKNOWN,NaN,Takeaway,2023-01-10
43,TXN_9620080,Juice,4,3.0,12.0,NaN,Takeaway,2023-10-02
44,TXN_1491578,Cookie,2,1.0,2.0,NaN,NaN,2023-02-23
45,TXN_5455792,Salad,3,5.0,15.0,Cash,NaN,2023-03-22
46,TXN_8078640,Juice,4,3.0,12.0,Digital Wallet,In-store,2023-11-03
47,TXN_9499313,Juice,5,3.0,15.0,NaN,NaN,2023-03-02
48,TXN_8201146,Juice,5,3.0,15.0,Cash,NaN,2023-06-26
49,TXN_8230936,Cake,3,3.0,9.0,NaN,NaN,2023-05-02

In [21]:
df["Total Spent"].unique()

<StringArray>
[    '4.0',    '12.0',   'ERROR',    '10.0',    '20.0',     '9.0',    '16.0',
    '15.0',    '25.0',     '8.0',     '5.0',     '3.0',     '6.0',       nan,
 'UNKNOWN',     '2.0',     '1.0',     '7.5',     '4.5',     '1.5']
Length: 20, dtype: str

In [22]:
df["Total Spent"]=df["Total Spent"].replace("ERROR",pd.NA)

In [23]:
df.head(20)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,NaN,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,NaN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
5,TXN_2602893,Smoothie,5,4.0,20.0,Credit Card,NaN,2023-03-31
6,TXN_4433211,UNKNOWN,3,3.0,9.0,ERROR,Takeaway,2023-10-06
7,TXN_6699534,Sandwich,4,4.0,16.0,Cash,NaN,2023-10-28
8,TXN_4717867,NaN,5,3.0,15.0,NaN,Takeaway,2023-07-28
9,TXN_2064365,Sandwich,5,4.0,20.0,NaN,In-store,2023-12-31
10,TXN_2548360,Salad,5,5.0,25.0,Cash,Takeaway,2023-11-07
11,TXN_3051279,Sandwich,2,4.0,8.0,Credit Card,Takeaway,ERROR
12,TXN_7619095,Sandwich,2,4.0,8.0,Cash,In-store,2023-05-03
13,TXN_9437049,Cookie,5,1.0,5.0,NaN,Takeaway,2023-06-01
14,TXN_8915701,ERROR,2,1.5,3.0,NaN,In-store,2023-03-21
15,TXN_2847255,Salad,3,5.0,15.0,Credit Card,In-store,2023-11-15
16,TXN_3765707,Sandwich,1,4.0,4.0,NaN,NaN,2023-06-10
17,TXN_6769710,Juice,2,3.0,6.0,Cash,In-store,2023-02-24
18,TXN_8876618,Cake,5,3.0,15.0,Cash,NaN,2023-03-25
19,TXN_3709394,Juice,4,3.0,12.0,Cash,Takeaway,2023-01-15

In [28]:
df["Total Spent"]=df["Total Spent"].replace("UNKNOWN",pd.NA)
df

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,NaN,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,NaN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,NaN,2023-08-30
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [29]:
df.head(30)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,NaN,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,NaN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
5,TXN_2602893,Smoothie,5,4.0,20.0,Credit Card,NaN,2023-03-31
6,TXN_4433211,UNKNOWN,3,3.0,9.0,ERROR,Takeaway,2023-10-06
7,TXN_6699534,Sandwich,4,4.0,16.0,Cash,NaN,2023-10-28
8,TXN_4717867,NaN,5,3.0,15.0,NaN,Takeaway,2023-07-28
9,TXN_2064365,Sandwich,5,4.0,20.0,NaN,In-store,2023-12-31
10,TXN_2548360,Salad,5,5.0,25.0,Cash,Takeaway,2023-11-07
11,TXN_3051279,Sandwich,2,4.0,8.0,Credit Card,Takeaway,ERROR
12,TXN_7619095,Sandwich,2,4.0,8.0,Cash,In-store,2023-05-03
13,TXN_9437049,Cookie,5,1.0,5.0,NaN,Takeaway,2023-06-01
14,TXN_8915701,ERROR,2,1.5,3.0,NaN,In-store,2023-03-21
15,TXN_2847255,Salad,3,5.0,15.0,Credit Card,In-store,2023-11-15
16,TXN_3765707,Sandwich,1,4.0,4.0,NaN,NaN,2023-06-10
17,TXN_6769710,Juice,2,3.0,6.0,Cash,In-store,2023-02-24
18,TXN_8876618,Cake,5,3.0,15.0,Cash,NaN,2023-03-25
19,TXN_3709394,Juice,4,3.0,12.0,Cash,Takeaway,2023-01-15
20,TXN_3522028,Smoothie,ERROR,4.0,20.0,Cash,In-store,2023-04-04
21,TXN_3567645,Smoothie,4,4.0,16.0,Credit Card,Takeaway,2023-03-30
22,TXN_5132361,Sandwich,3,4.0,12.0,Digital Wallet,Takeaway,2023-12-01
23,TXN_2616390,Sandwich,2,4.0,8.0,NaN,NaN,2023-09-18
24,TXN_9400181,Sandwich,5,4.0,20.0,Cash,In-store,2023-06-03
25,TXN_7958992,Smoothie,3,4.0,NaN,UNKNOWN,NaN,2023-12-13
26,TXN_5183041,Cookie,5,1.0,5.0,Credit Card,In-store,2023-04-20
27,TXN_5695074,Juice,4,3.0,12.0,Credit Card,Takeaway,2023-04-10
28,TXN_8467949,Smoothie,5,4.0,20.0,Credit Card,NaN,2023-03-11
29,TXN_7640952,Cake,4,3.0,12.0,Digital Wallet,Takeaway,ERROR

In [30]:
df["Total Spent"].unique()

<StringArray>
[ '4.0', '12.0',    nan, '10.0', '20.0',  '9.0', '16.0', '15.0', '25.0',
  '8.0',  '5.0',  '3.0',  '6.0',  '2.0',  '1.0',  '7.5',  '4.5',  '1.5']
Length: 18, dtype: str

In [33]:
df["Total Spent"]=pd.to_numeric(df["Total Spent"],errors="coerce")

In [36]:
df
avg=df["Total Spent"].mean()

In [40]:
df["Total Spent"] = df["Total Spent"].fillna(avg)

In [41]:
df.head(30)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.000000,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.000000,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,8.924352,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.000000,UNKNOWN,NaN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.000000,Digital Wallet,In-store,2023-06-11
5,TXN_2602893,Smoothie,5,4.0,20.000000,Credit Card,NaN,2023-03-31
6,TXN_4433211,UNKNOWN,3,3.0,9.000000,ERROR,Takeaway,2023-10-06
7,TXN_6699534,Sandwich,4,4.0,16.000000,Cash,NaN,2023-10-28
8,TXN_4717867,NaN,5,3.0,15.000000,NaN,Takeaway,2023-07-28
9,TXN_2064365,Sandwich,5,4.0,20.000000,NaN,In-store,2023-12-31
10,TXN_2548360,Salad,5,5.0,25.000000,Cash,Takeaway,2023-11-07
11,TXN_3051279,Sandwich,2,4.0,8.000000,Credit Card,Takeaway,ERROR
12,TXN_7619095,Sandwich,2,4.0,8.000000,Cash,In-store,2023-05-03
13,TXN_9437049,Cookie,5,1.0,5.000000,NaN,Takeaway,2023-06-01
14,TXN_8915701,ERROR,2,1.5,3.000000,NaN,In-store,2023-03-21
15,TXN_2847255,Salad,3,5.0,15.000000,Credit Card,In-store,2023-11-15
16,TXN_3765707,Sandwich,1,4.0,4.000000,NaN,NaN,2023-06-10
17,TXN_6769710,Juice,2,3.0,6.000000,Cash,In-store,2023-02-24
18,TXN_8876618,Cake,5,3.0,15.000000,Cash,NaN,2023-03-25
19,TXN_3709394,Juice,4,3.0,12.000000,Cash,Takeaway,2023-01-15
20,TXN_3522028,Smoothie,ERROR,4.0,20.000000,Cash,In-store,2023-04-04
21,TXN_3567645,Smoothie,4,4.0,16.000000,Credit Card,Takeaway,2023-03-30
22,TXN_5132361,Sandwich,3,4.0,12.000000,Digital Wallet,Takeaway,2023-12-01
23,TXN_2616390,Sandwich,2,4.0,8.000000,NaN,NaN,2023-09-18
24,TXN_9400181,Sandwich,5,4.0,20.000000,Cash,In-store,2023-06-03
25,TXN_7958992,Smoothie,3,4.0,8.924352,UNKNOWN,NaN,2023-12-13
26,TXN_5183041,Cookie,5,1.0,5.000000,Credit Card,In-store,2023-04-20
27,TXN_5695074,Juice,4,3.0,12.000000,Credit Card,Takeaway,2023-04-10
28,TXN_8467949,Smoothie,5,4.0,20.000000,Credit Card,NaN,2023-03-11
29,TXN_7640952,Cake,4,3.0,12.000000,Digital Wallet,Takeaway,ERROR

In [42]:
df["Item"].unique()

<StringArray>
[  'Coffee',     'Cake',   'Cookie',    'Salad', 'Smoothie',  'UNKNOWN',
 'Sandwich',        nan,    'ERROR',    'Juice',      'Tea']
Length: 11, dtype: str

In [43]:
df = df.dropna(subset=["Item"])

In [45]:
df.head(30)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.000000,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.000000,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,8.924352,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.000000,UNKNOWN,NaN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.000000,Digital Wallet,In-store,2023-06-11
5,TXN_2602893,Smoothie,5,4.0,20.000000,Credit Card,NaN,2023-03-31
6,TXN_4433211,UNKNOWN,3,3.0,9.000000,ERROR,Takeaway,2023-10-06
7,TXN_6699534,Sandwich,4,4.0,16.000000,Cash,NaN,2023-10-28
9,TXN_2064365,Sandwich,5,4.0,20.000000,NaN,In-store,2023-12-31
10,TXN_2548360,Salad,5,5.0,25.000000,Cash,Takeaway,2023-11-07
11,TXN_3051279,Sandwich,2,4.0,8.000000,Credit Card,Takeaway,ERROR
12,TXN_7619095,Sandwich,2,4.0,8.000000,Cash,In-store,2023-05-03
13,TXN_9437049,Cookie,5,1.0,5.000000,NaN,Takeaway,2023-06-01
14,TXN_8915701,ERROR,2,1.5,3.000000,NaN,In-store,2023-03-21
15,TXN_2847255,Salad,3,5.0,15.000000,Credit Card,In-store,2023-11-15
16,TXN_3765707,Sandwich,1,4.0,4.000000,NaN,NaN,2023-06-10
17,TXN_6769710,Juice,2,3.0,6.000000,Cash,In-store,2023-02-24
18,TXN_8876618,Cake,5,3.0,15.000000,Cash,NaN,2023-03-25
19,TXN_3709394,Juice,4,3.0,12.000000,Cash,Takeaway,2023-01-15
20,TXN_3522028,Smoothie,ERROR,4.0,20.000000,Cash,In-store,2023-04-04
21,TXN_3567645,Smoothie,4,4.0,16.000000,Credit Card,Takeaway,2023-03-30
22,TXN_5132361,Sandwich,3,4.0,12.000000,Digital Wallet,Takeaway,2023-12-01
23,TXN_2616390,Sandwich,2,4.0,8.000000,NaN,NaN,2023-09-18
24,TXN_9400181,Sandwich,5,4.0,20.000000,Cash,In-store,2023-06-03
25,TXN_7958992,Smoothie,3,4.0,8.924352,UNKNOWN,NaN,2023-12-13
26,TXN_5183041,Cookie,5,1.0,5.000000,Credit Card,In-store,2023-04-20
27,TXN_5695074,Juice,4,3.0,12.000000,Credit Card,Takeaway,2023-04-10
28,TXN_8467949,Smoothie,5,4.0,20.000000,Credit Card,NaN,2023-03-11
29,TXN_7640952,Cake,4,3.0,12.000000,Digital Wallet,Takeaway,ERROR
31,TXN_8927252,UNKNOWN,2,1.0,8.924352,Credit Card,NaN,2023-11-06

In [47]:
df["Item"]=df["Item"].replace("UNKNOWN",pd.NA)
df["Item"]=df["Item"].replace("ERROR",pd.NA)

In [48]:
df.head(50)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.000000,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.000000,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,8.924352,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.000000,UNKNOWN,NaN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.000000,Digital Wallet,In-store,2023-06-11
5,TXN_2602893,Smoothie,5,4.0,20.000000,Credit Card,NaN,2023-03-31
6,TXN_4433211,NaN,3,3.0,9.000000,ERROR,Takeaway,2023-10-06
7,TXN_6699534,Sandwich,4,4.0,16.000000,Cash,NaN,2023-10-28
9,TXN_2064365,Sandwich,5,4.0,20.000000,NaN,In-store,2023-12-31
10,TXN_2548360,Salad,5,5.0,25.000000,Cash,Takeaway,2023-11-07
11,TXN_3051279,Sandwich,2,4.0,8.000000,Credit Card,Takeaway,ERROR
12,TXN_7619095,Sandwich,2,4.0,8.000000,Cash,In-store,2023-05-03
13,TXN_9437049,Cookie,5,1.0,5.000000,NaN,Takeaway,2023-06-01
14,TXN_8915701,NaN,2,1.5,3.000000,NaN,In-store,2023-03-21
15,TXN_2847255,Salad,3,5.0,15.000000,Credit Card,In-store,2023-11-15
16,TXN_3765707,Sandwich,1,4.0,4.000000,NaN,NaN,2023-06-10
17,TXN_6769710,Juice,2,3.0,6.000000,Cash,In-store,2023-02-24
18,TXN_8876618,Cake,5,3.0,15.000000,Cash,NaN,2023-03-25
19,TXN_3709394,Juice,4,3.0,12.000000,Cash,Takeaway,2023-01-15
20,TXN_3522028,Smoothie,ERROR,4.0,20.000000,Cash,In-store,2023-04-04
21,TXN_3567645,Smoothie,4,4.0,16.000000,Credit Card,Takeaway,2023-03-30
22,TXN_5132361,Sandwich,3,4.0,12.000000,Digital Wallet,Takeaway,2023-12-01
23,TXN_2616390,Sandwich,2,4.0,8.000000,NaN,NaN,2023-09-18
24,TXN_9400181,Sandwich,5,4.0,20.000000,Cash,In-store,2023-06-03
25,TXN_7958992,Smoothie,3,4.0,8.924352,UNKNOWN,NaN,2023-12-13
26,TXN_5183041,Cookie,5,1.0,5.000000,Credit Card,In-store,2023-04-20
27,TXN_5695074,Juice,4,3.0,12.000000,Credit Card,Takeaway,2023-04-10
28,TXN_8467949,Smoothie,5,4.0,20.000000,Credit Card,NaN,2023-03-11
29,TXN_7640952,Cake,4,3.0,12.000000,Digital Wallet,Takeaway,ERROR
31,TXN_8927252,NaN,2,1.0,8.924352,Credit Card,NaN,2023-11-06
32,TXN_9677376,Smoothie,4,4.0,16.000000,NaN,In-store,2023-08-15
33,TXN_7710508,NaN,5,1.0,5.000000,Cash,NaN,ERROR
34,TXN_8853997,Smoothie,2,4.0,8.000000,Digital Wallet,Takeaway,2023-10-09
35,TXN_9130559,Sandwich,1,4.0,4.000000,Credit Card,NaN,2023-05-28
36,TXN_6855453,NaN,4,3.0,12.000000,NaN,In-store,2023-07-17
37,TXN_1080432,Salad,2,5.0,10.000000,Credit Card,In-store,2023-04-29
38,TXN_2655815,Smoothie,4,4.0,16.000000,NaN,Takeaway,2023-06-08
39,TXN_6688524,Coffee,4,2.0,8.000000,ERROR,NaN,2023-06-29
40,TXN_2083138,Smoothie,3,4.0,12.000000,NaN,In-store,2023-04-17
41,TXN_2427584,Sandwich,4,4.0,16.000000,NaN,Takeaway,2023-12-22
42,TXN_6650263,Tea,2,1.5,8.924352,NaN,Takeaway,2023-01-10
43,TXN_9620080,Juice,4,3.0,12.000000,NaN,Takeaway,2023-10-02
44,TXN_1491578,Cookie,2,1.0,2.000000,NaN,NaN,2023-02-23
45,TXN_5455792,Salad,3,5.0,15.000000,Cash,NaN,2023-03-22
46,TXN_8078640,Juice,4,3.0,12.000000,Digital Wallet,In-store,2023-11-03
47,TXN_9499313,Juice,5,3.0,15.000000,NaN,NaN,2023-03-02
48,TXN_8201146,Juice,5,3.0,15.000000,Cash,NaN,2023-06-26
49,TXN_8230936,Cake,3,3.0,9.000000,NaN,NaN,2023-05-02
50,TXN_7742742,Cake,5,3.0,15.000000,NaN,Takeaway,2023-09-05
51,TXN_6342161,Salad,5,5.0,25.000000,ERROR,Takeaway,2023-01-08

In [49]:
df=df.dropna(subset=["Item"])

In [50]:
df.head(50)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.000000,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.000000,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,8.924352,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.000000,UNKNOWN,NaN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.000000,Digital Wallet,In-store,2023-06-11
5,TXN_2602893,Smoothie,5,4.0,20.000000,Credit Card,NaN,2023-03-31
7,TXN_6699534,Sandwich,4,4.0,16.000000,Cash,NaN,2023-10-28
9,TXN_2064365,Sandwich,5,4.0,20.000000,NaN,In-store,2023-12-31
10,TXN_2548360,Salad,5,5.0,25.000000,Cash,Takeaway,2023-11-07
11,TXN_3051279,Sandwich,2,4.0,8.000000,Credit Card,Takeaway,ERROR
12,TXN_7619095,Sandwich,2,4.0,8.000000,Cash,In-store,2023-05-03
13,TXN_9437049,Cookie,5,1.0,5.000000,NaN,Takeaway,2023-06-01
15,TXN_2847255,Salad,3,5.0,15.000000,Credit Card,In-store,2023-11-15
16,TXN_3765707,Sandwich,1,4.0,4.000000,NaN,NaN,2023-06-10
17,TXN_6769710,Juice,2,3.0,6.000000,Cash,In-store,2023-02-24
18,TXN_8876618,Cake,5,3.0,15.000000,Cash,NaN,2023-03-25
19,TXN_3709394,Juice,4,3.0,12.000000,Cash,Takeaway,2023-01-15
20,TXN_3522028,Smoothie,ERROR,4.0,20.000000,Cash,In-store,2023-04-04
21,TXN_3567645,Smoothie,4,4.0,16.000000,Credit Card,Takeaway,2023-03-30
22,TXN_5132361,Sandwich,3,4.0,12.000000,Digital Wallet,Takeaway,2023-12-01
23,TXN_2616390,Sandwich,2,4.0,8.000000,NaN,NaN,2023-09-18
24,TXN_9400181,Sandwich,5,4.0,20.000000,Cash,In-store,2023-06-03
25,TXN_7958992,Smoothie,3,4.0,8.924352,UNKNOWN,NaN,2023-12-13
26,TXN_5183041,Cookie,5,1.0,5.000000,Credit Card,In-store,2023-04-20
27,TXN_5695074,Juice,4,3.0,12.000000,Credit Card,Takeaway,2023-04-10
28,TXN_8467949,Smoothie,5,4.0,20.000000,Credit Card,NaN,2023-03-11
29,TXN_7640952,Cake,4,3.0,12.000000,Digital Wallet,Takeaway,ERROR
32,TXN_9677376,Smoothie,4,4.0,16.000000,NaN,In-store,2023-08-15
34,TXN_8853997,Smoothie,2,4.0,8.000000,Digital Wallet,Takeaway,2023-10-09
35,TXN_9130559,Sandwich,1,4.0,4.000000,Credit Card,NaN,2023-05-28
37,TXN_1080432,Salad,2,5.0,10.000000,Credit Card,In-store,2023-04-29
38,TXN_2655815,Smoothie,4,4.0,16.000000,NaN,Takeaway,2023-06-08
39,TXN_6688524,Coffee,4,2.0,8.000000,ERROR,NaN,2023-06-29
40,TXN_2083138,Smoothie,3,4.0,12.000000,NaN,In-store,2023-04-17
41,TXN_2427584,Sandwich,4,4.0,16.000000,NaN,Takeaway,2023-12-22
42,TXN_6650263,Tea,2,1.5,8.924352,NaN,Takeaway,2023-01-10
43,TXN_9620080,Juice,4,3.0,12.000000,NaN,Takeaway,2023-10-02
44,TXN_1491578,Cookie,2,1.0,2.000000,NaN,NaN,2023-02-23
45,TXN_5455792,Salad,3,5.0,15.000000,Cash,NaN,2023-03-22
46,TXN_8078640,Juice,4,3.0,12.000000,Digital Wallet,In-store,2023-11-03
47,TXN_9499313,Juice,5,3.0,15.000000,NaN,NaN,2023-03-02
48,TXN_8201146,Juice,5,3.0,15.000000,Cash,NaN,2023-06-26
49,TXN_8230936,Cake,3,3.0,9.000000,NaN,NaN,2023-05-02
50,TXN_7742742,Cake,5,3.0,15.000000,NaN,Takeaway,2023-09-05
51,TXN_6342161,Salad,5,5.0,25.000000,ERROR,Takeaway,2023-01-08
53,TXN_3363746,Smoothie,3,4.0,12.000000,Credit Card,NaN,2023-11-25
54,TXN_8614868,Smoothie,5,4.0,20.000000,Digital Wallet,Takeaway,2023-12-05
55,TXN_5522862,Cookie,ERROR,1.0,2.000000,Credit Card,Takeaway,2023-03-19
56,TXN_3578141,Cake,5,NaN,15.000000,NaN,Takeaway,2023-06-27
57,TXN_2080895,Cake,UNKNOWN,3.0,3.000000,Digital Wallet,In-store,2023-04-19

In [51]:
df["Quantity"].unique()

<StringArray>
['2', '4', '5', '3', '1', 'ERROR', 'UNKNOWN', nan]
Length: 8, dtype: str

In [52]:
df["Quantity"]=pd.to_numeric(df["Quantity"], errors="coerce")

In [54]:
avg1=df["Quantity"].mean()
df["Quantity"]=df["Quantity"].fillna(avg1)

In [55]:
df.head(45)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2.000000,2.0,4.000000,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4.000000,3.0,12.000000,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4.000000,1.0,8.924352,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2.000000,5.0,10.000000,UNKNOWN,NaN,2023-04-27
4,TXN_3160411,Coffee,2.000000,2.0,4.000000,Digital Wallet,In-store,2023-06-11
5,TXN_2602893,Smoothie,5.000000,4.0,20.000000,Credit Card,NaN,2023-03-31
7,TXN_6699534,Sandwich,4.000000,4.0,16.000000,Cash,NaN,2023-10-28
9,TXN_2064365,Sandwich,5.000000,4.0,20.000000,NaN,In-store,2023-12-31
10,TXN_2548360,Salad,5.000000,5.0,25.000000,Cash,Takeaway,2023-11-07
11,TXN_3051279,Sandwich,2.000000,4.0,8.000000,Credit Card,Takeaway,ERROR
12,TXN_7619095,Sandwich,2.000000,4.0,8.000000,Cash,In-store,2023-05-03
13,TXN_9437049,Cookie,5.000000,1.0,5.000000,NaN,Takeaway,2023-06-01
15,TXN_2847255,Salad,3.000000,5.0,15.000000,Credit Card,In-store,2023-11-15
16,TXN_3765707,Sandwich,1.000000,4.0,4.000000,NaN,NaN,2023-06-10
17,TXN_6769710,Juice,2.000000,3.0,6.000000,Cash,In-store,2023-02-24
18,TXN_8876618,Cake,5.000000,3.0,15.000000,Cash,NaN,2023-03-25
19,TXN_3709394,Juice,4.000000,3.0,12.000000,Cash,Takeaway,2023-01-15
20,TXN_3522028,Smoothie,3.029846,4.0,20.000000,Cash,In-store,2023-04-04
21,TXN_3567645,Smoothie,4.000000,4.0,16.000000,Credit Card,Takeaway,2023-03-30
22,TXN_5132361,Sandwich,3.000000,4.0,12.000000,Digital Wallet,Takeaway,2023-12-01
23,TXN_2616390,Sandwich,2.000000,4.0,8.000000,NaN,NaN,2023-09-18
24,TXN_9400181,Sandwich,5.000000,4.0,20.000000,Cash,In-store,2023-06-03
25,TXN_7958992,Smoothie,3.000000,4.0,8.924352,UNKNOWN,NaN,2023-12-13
26,TXN_5183041,Cookie,5.000000,1.0,5.000000,Credit Card,In-store,2023-04-20
27,TXN_5695074,Juice,4.000000,3.0,12.000000,Credit Card,Takeaway,2023-04-10
28,TXN_8467949,Smoothie,5.000000,4.0,20.000000,Credit Card,NaN,2023-03-11
29,TXN_7640952,Cake,4.000000,3.0,12.000000,Digital Wallet,Takeaway,ERROR
32,TXN_9677376,Smoothie,4.000000,4.0,16.000000,NaN,In-store,2023-08-15
34,TXN_8853997,Smoothie,2.000000,4.0,8.000000,Digital Wallet,Takeaway,2023-10-09
35,TXN_9130559,Sandwich,1.000000,4.0,4.000000,Credit Card,NaN,2023-05-28
37,TXN_1080432,Salad,2.000000,5.0,10.000000,Credit Card,In-store,2023-04-29
38,TXN_2655815,Smoothie,4.000000,4.0,16.000000,NaN,Takeaway,2023-06-08
39,TXN_6688524,Coffee,4.000000,2.0,8.000000,ERROR,NaN,2023-06-29
40,TXN_2083138,Smoothie,3.000000,4.0,12.000000,NaN,In-store,2023-04-17
41,TXN_2427584,Sandwich,4.000000,4.0,16.000000,NaN,Takeaway,2023-12-22
42,TXN_6650263,Tea,2.000000,1.5,8.924352,NaN,Takeaway,2023-01-10
43,TXN_9620080,Juice,4.000000,3.0,12.000000,NaN,Takeaway,2023-10-02
44,TXN_1491578,Cookie,2.000000,1.0,2.000000,NaN,NaN,2023-02-23
45,TXN_5455792,Salad,3.000000,5.0,15.000000,Cash,NaN,2023-03-22
46,TXN_8078640,Juice,4.000000,3.0,12.000000,Digital Wallet,In-store,2023-11-03
47,TXN_9499313,Juice,5.000000,3.0,15.000000,NaN,NaN,2023-03-02
48,TXN_8201146,Juice,5.000000,3.0,15.000000,Cash,NaN,2023-06-26
49,TXN_8230936,Cake,3.000000,3.0,9.000000,NaN,NaN,2023-05-02
50,TXN_7742742,Cake,5.000000,3.0,15.000000,NaN,Takeaway,2023-09-05
51,TXN_6342161,Salad,5.000000,5.0,25.000000,ERROR,Takeaway,2023-01-08

In [56]:
df["Payment Method"].unique()

<StringArray>
['Credit Card', 'Cash', 'UNKNOWN', 'Digital Wallet', nan, 'ERROR']
Length: 6, dtype: str

In [57]:
df["Payment Method"]=df["Payment Method"].replace("ERROR",pd.NA)
df["Payment Method"]=df["Payment Method"].replace("UNKNOWN",pd.NA)

In [58]:
df.head(50)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2.000000,2.0,4.000000,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4.000000,3.0,12.000000,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4.000000,1.0,8.924352,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2.000000,5.0,10.000000,NaN,NaN,2023-04-27
4,TXN_3160411,Coffee,2.000000,2.0,4.000000,Digital Wallet,In-store,2023-06-11
5,TXN_2602893,Smoothie,5.000000,4.0,20.000000,Credit Card,NaN,2023-03-31
7,TXN_6699534,Sandwich,4.000000,4.0,16.000000,Cash,NaN,2023-10-28
9,TXN_2064365,Sandwich,5.000000,4.0,20.000000,NaN,In-store,2023-12-31
10,TXN_2548360,Salad,5.000000,5.0,25.000000,Cash,Takeaway,2023-11-07
11,TXN_3051279,Sandwich,2.000000,4.0,8.000000,Credit Card,Takeaway,ERROR
12,TXN_7619095,Sandwich,2.000000,4.0,8.000000,Cash,In-store,2023-05-03
13,TXN_9437049,Cookie,5.000000,1.0,5.000000,NaN,Takeaway,2023-06-01
15,TXN_2847255,Salad,3.000000,5.0,15.000000,Credit Card,In-store,2023-11-15
16,TXN_3765707,Sandwich,1.000000,4.0,4.000000,NaN,NaN,2023-06-10
17,TXN_6769710,Juice,2.000000,3.0,6.000000,Cash,In-store,2023-02-24
18,TXN_8876618,Cake,5.000000,3.0,15.000000,Cash,NaN,2023-03-25
19,TXN_3709394,Juice,4.000000,3.0,12.000000,Cash,Takeaway,2023-01-15
20,TXN_3522028,Smoothie,3.029846,4.0,20.000000,Cash,In-store,2023-04-04
21,TXN_3567645,Smoothie,4.000000,4.0,16.000000,Credit Card,Takeaway,2023-03-30
22,TXN_5132361,Sandwich,3.000000,4.0,12.000000,Digital Wallet,Takeaway,2023-12-01
23,TXN_2616390,Sandwich,2.000000,4.0,8.000000,NaN,NaN,2023-09-18
24,TXN_9400181,Sandwich,5.000000,4.0,20.000000,Cash,In-store,2023-06-03
25,TXN_7958992,Smoothie,3.000000,4.0,8.924352,NaN,NaN,2023-12-13
26,TXN_5183041,Cookie,5.000000,1.0,5.000000,Credit Card,In-store,2023-04-20
27,TXN_5695074,Juice,4.000000,3.0,12.000000,Credit Card,Takeaway,2023-04-10
28,TXN_8467949,Smoothie,5.000000,4.0,20.000000,Credit Card,NaN,2023-03-11
29,TXN_7640952,Cake,4.000000,3.0,12.000000,Digital Wallet,Takeaway,ERROR
32,TXN_9677376,Smoothie,4.000000,4.0,16.000000,NaN,In-store,2023-08-15
34,TXN_8853997,Smoothie,2.000000,4.0,8.000000,Digital Wallet,Takeaway,2023-10-09
35,TXN_9130559,Sandwich,1.000000,4.0,4.000000,Credit Card,NaN,2023-05-28
37,TXN_1080432,Salad,2.000000,5.0,10.000000,Credit Card,In-store,2023-04-29
38,TXN_2655815,Smoothie,4.000000,4.0,16.000000,NaN,Takeaway,2023-06-08
39,TXN_6688524,Coffee,4.000000,2.0,8.000000,NaN,NaN,2023-06-29
40,TXN_2083138,Smoothie,3.000000,4.0,12.000000,NaN,In-store,2023-04-17
41,TXN_2427584,Sandwich,4.000000,4.0,16.000000,NaN,Takeaway,2023-12-22
42,TXN_6650263,Tea,2.000000,1.5,8.924352,NaN,Takeaway,2023-01-10
43,TXN_9620080,Juice,4.000000,3.0,12.000000,NaN,Takeaway,2023-10-02
44,TXN_1491578,Cookie,2.000000,1.0,2.000000,NaN,NaN,2023-02-23
45,TXN_5455792,Salad,3.000000,5.0,15.000000,Cash,NaN,2023-03-22
46,TXN_8078640,Juice,4.000000,3.0,12.000000,Digital Wallet,In-store,2023-11-03
47,TXN_9499313,Juice,5.000000,3.0,15.000000,NaN,NaN,2023-03-02
48,TXN_8201146,Juice,5.000000,3.0,15.000000,Cash,NaN,2023-06-26
49,TXN_8230936,Cake,3.000000,3.0,9.000000,NaN,NaN,2023-05-02
50,TXN_7742742,Cake,5.000000,3.0,15.000000,NaN,Takeaway,2023-09-05
51,TXN_6342161,Salad,5.000000,5.0,25.000000,NaN,Takeaway,2023-01-08
53,TXN_3363746,Smoothie,3.000000,4.0,12.000000,Credit Card,NaN,2023-11-25
54,TXN_8614868,Smoothie,5.000000,4.0,20.000000,Digital Wallet,Takeaway,2023-12-05
55,TXN_5522862,Cookie,3.029846,1.0,2.000000,Credit Card,Takeaway,2023-03-19
56,TXN_3578141,Cake,5.000000,NaN,15.000000,NaN,Takeaway,2023-06-27
57,TXN_2080895,Cake,3.029846,3.0,3.000000,Digital Wallet,In-store,2023-04-19

In [59]:
df["Payment Method"]=df["Payment Method"].fillna("Cash")

In [60]:
df.head(57)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2.000000,2.0,4.000000,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4.000000,3.0,12.000000,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4.000000,1.0,8.924352,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2.000000,5.0,10.000000,Cash,NaN,2023-04-27
4,TXN_3160411,Coffee,2.000000,2.0,4.000000,Digital Wallet,In-store,2023-06-11
5,TXN_2602893,Smoothie,5.000000,4.0,20.000000,Credit Card,NaN,2023-03-31
7,TXN_6699534,Sandwich,4.000000,4.0,16.000000,Cash,NaN,2023-10-28
9,TXN_2064365,Sandwich,5.000000,4.0,20.000000,Cash,In-store,2023-12-31
10,TXN_2548360,Salad,5.000000,5.0,25.000000,Cash,Takeaway,2023-11-07
11,TXN_3051279,Sandwich,2.000000,4.0,8.000000,Credit Card,Takeaway,ERROR
12,TXN_7619095,Sandwich,2.000000,4.0,8.000000,Cash,In-store,2023-05-03
13,TXN_9437049,Cookie,5.000000,1.0,5.000000,Cash,Takeaway,2023-06-01
15,TXN_2847255,Salad,3.000000,5.0,15.000000,Credit Card,In-store,2023-11-15
16,TXN_3765707,Sandwich,1.000000,4.0,4.000000,Cash,NaN,2023-06-10
17,TXN_6769710,Juice,2.000000,3.0,6.000000,Cash,In-store,2023-02-24
18,TXN_8876618,Cake,5.000000,3.0,15.000000,Cash,NaN,2023-03-25
19,TXN_3709394,Juice,4.000000,3.0,12.000000,Cash,Takeaway,2023-01-15
20,TXN_3522028,Smoothie,3.029846,4.0,20.000000,Cash,In-store,2023-04-04
21,TXN_3567645,Smoothie,4.000000,4.0,16.000000,Credit Card,Takeaway,2023-03-30
22,TXN_5132361,Sandwich,3.000000,4.0,12.000000,Digital Wallet,Takeaway,2023-12-01
23,TXN_2616390,Sandwich,2.000000,4.0,8.000000,Cash,NaN,2023-09-18
24,TXN_9400181,Sandwich,5.000000,4.0,20.000000,Cash,In-store,2023-06-03
25,TXN_7958992,Smoothie,3.000000,4.0,8.924352,Cash,NaN,2023-12-13
26,TXN_5183041,Cookie,5.000000,1.0,5.000000,Credit Card,In-store,2023-04-20
27,TXN_5695074,Juice,4.000000,3.0,12.000000,Credit Card,Takeaway,2023-04-10
28,TXN_8467949,Smoothie,5.000000,4.0,20.000000,Credit Card,NaN,2023-03-11
29,TXN_7640952,Cake,4.000000,3.0,12.000000,Digital Wallet,Takeaway,ERROR
32,TXN_9677376,Smoothie,4.000000,4.0,16.000000,Cash,In-store,2023-08-15
34,TXN_8853997,Smoothie,2.000000,4.0,8.000000,Digital Wallet,Takeaway,2023-10-09
35,TXN_9130559,Sandwich,1.000000,4.0,4.000000,Credit Card,NaN,2023-05-28
37,TXN_1080432,Salad,2.000000,5.0,10.000000,Credit Card,In-store,2023-04-29
38,TXN_2655815,Smoothie,4.000000,4.0,16.000000,Cash,Takeaway,2023-06-08
39,TXN_6688524,Coffee,4.000000,2.0,8.000000,Cash,NaN,2023-06-29
40,TXN_2083138,Smoothie,3.000000,4.0,12.000000,Cash,In-store,2023-04-17
41,TXN_2427584,Sandwich,4.000000,4.0,16.000000,Cash,Takeaway,2023-12-22
42,TXN_6650263,Tea,2.000000,1.5,8.924352,Cash,Takeaway,2023-01-10
43,TXN_9620080,Juice,4.000000,3.0,12.000000,Cash,Takeaway,2023-10-02
44,TXN_1491578,Cookie,2.000000,1.0,2.000000,Cash,NaN,2023-02-23
45,TXN_5455792,Salad,3.000000,5.0,15.000000,Cash,NaN,2023-03-22
46,TXN_8078640,Juice,4.000000,3.0,12.000000,Digital Wallet,In-store,2023-11-03
47,TXN_9499313,Juice,5.000000,3.0,15.000000,Cash,NaN,2023-03-02
48,TXN_8201146,Juice,5.000000,3.0,15.000000,Cash,NaN,2023-06-26
49,TXN_8230936,Cake,3.000000,3.0,9.000000,Cash,NaN,2023-05-02
50,TXN_7742742,Cake,5.000000,3.0,15.000000,Cash,Takeaway,2023-09-05
51,TXN_6342161,Salad,5.000000,5.0,25.000000,Cash,Takeaway,2023-01-08
53,TXN_3363746,Smoothie,3.000000,4.0,12.000000,Credit Card,NaN,2023-11-25
54,TXN_8614868,Smoothie,5.000000,4.0,20.000000,Digital Wallet,Takeaway,2023-12-05
55,TXN_5522862,Cookie,3.029846,1.0,2.000000,Credit Card,Takeaway,2023-03-19
56,TXN_3578141,Cake,5.000000,NaN,15.000000,Cash,Takeaway,2023-06-27
57,TXN_2080895,Cake,3.029846,3.0,3.000000,Digital Wallet,In-store,2023-04-19
58,TXN_6421134,Sandwich,4.000000,4.0,16.000000,Cash,Takeaway,2023-11-03
59,TXN_8813311,Juice,5.000000,3.0,15.000000,Cash,In-store,2023-10-07
60,TXN_9023317,Salad,1.000000,5.0,5.000000,Cash,NaN,2023-09-30
62,TXN_2537617,Sandwich,1.000000,4.0,4.000000,Cash,NaN,2023-05-27
64,TXN_9230615,Smoothie,4.000000,4.0,16.000000,Digital Wallet,NaN,2023-06-01
65,TXN_4987129,Sandwich,3.000000,NaN,8.924352,Cash,In-store,2023-10-20
66,TXN_8501819,Juice,3.029846,3.0,6.000000,Cash,NaN,2023-03-30

In [61]:
df

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2.0,2.0,4.000000,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4.0,3.0,12.000000,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4.0,1.0,8.924352,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2.0,5.0,10.000000,Cash,NaN,2023-04-27
4,TXN_3160411,Coffee,2.0,2.0,4.000000,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9993,TXN_4766549,Smoothie,2.0,4.0,8.924352,Cash,NaN,2023-10-20
9995,TXN_7672686,Coffee,2.0,2.0,4.000000,Cash,NaN,2023-08-30
9997,TXN_5255387,Coffee,4.0,2.0,8.000000,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3.0,NaN,3.000000,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3.0,4.0,12.000000,Cash,In-store,2023-11-07

In [64]:
df["Location"]=df["Location"].fillna("In-store")
df.head(80)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2.0,2.0,4.000000,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4.0,3.0,12.000000,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4.0,1.0,8.924352,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2.0,5.0,10.000000,Cash,In-store,2023-04-27
4,TXN_3160411,Coffee,2.0,2.0,4.000000,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
87,TXN_3955361,Cookie,5.0,1.0,5.000000,Cash,Takeaway,2023-04-02
90,TXN_8976658,Tea,2.0,1.5,3.000000,Credit Card,In-store,2023-08-16
92,TXN_2725602,Juice,5.0,3.0,15.000000,Credit Card,In-store,2023-09-10
93,TXN_3011323,Coffee,3.0,2.0,6.000000,Credit Card,In-store,2023-03-07
94,TXN_6289610,Juice,3.0,3.0,8.924352,Cash,Takeaway,2023-08-07

In [65]:
df.head(50)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2.000000,2.0,4.000000,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4.000000,3.0,12.000000,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4.000000,1.0,8.924352,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2.000000,5.0,10.000000,Cash,In-store,2023-04-27
4,TXN_3160411,Coffee,2.000000,2.0,4.000000,Digital Wallet,In-store,2023-06-11
5,TXN_2602893,Smoothie,5.000000,4.0,20.000000,Credit Card,In-store,2023-03-31
7,TXN_6699534,Sandwich,4.000000,4.0,16.000000,Cash,In-store,2023-10-28
9,TXN_2064365,Sandwich,5.000000,4.0,20.000000,Cash,In-store,2023-12-31
10,TXN_2548360,Salad,5.000000,5.0,25.000000,Cash,Takeaway,2023-11-07
11,TXN_3051279,Sandwich,2.000000,4.0,8.000000,Credit Card,Takeaway,ERROR
12,TXN_7619095,Sandwich,2.000000,4.0,8.000000,Cash,In-store,2023-05-03
13,TXN_9437049,Cookie,5.000000,1.0,5.000000,Cash,Takeaway,2023-06-01
15,TXN_2847255,Salad,3.000000,5.0,15.000000,Credit Card,In-store,2023-11-15
16,TXN_3765707,Sandwich,1.000000,4.0,4.000000,Cash,In-store,2023-06-10
17,TXN_6769710,Juice,2.000000,3.0,6.000000,Cash,In-store,2023-02-24
18,TXN_8876618,Cake,5.000000,3.0,15.000000,Cash,In-store,2023-03-25
19,TXN_3709394,Juice,4.000000,3.0,12.000000,Cash,Takeaway,2023-01-15
20,TXN_3522028,Smoothie,3.029846,4.0,20.000000,Cash,In-store,2023-04-04
21,TXN_3567645,Smoothie,4.000000,4.0,16.000000,Credit Card,Takeaway,2023-03-30
22,TXN_5132361,Sandwich,3.000000,4.0,12.000000,Digital Wallet,Takeaway,2023-12-01
23,TXN_2616390,Sandwich,2.000000,4.0,8.000000,Cash,In-store,2023-09-18
24,TXN_9400181,Sandwich,5.000000,4.0,20.000000,Cash,In-store,2023-06-03
25,TXN_7958992,Smoothie,3.000000,4.0,8.924352,Cash,In-store,2023-12-13
26,TXN_5183041,Cookie,5.000000,1.0,5.000000,Credit Card,In-store,2023-04-20
27,TXN_5695074,Juice,4.000000,3.0,12.000000,Credit Card,Takeaway,2023-04-10
28,TXN_8467949,Smoothie,5.000000,4.0,20.000000,Credit Card,In-store,2023-03-11
29,TXN_7640952,Cake,4.000000,3.0,12.000000,Digital Wallet,Takeaway,ERROR
32,TXN_9677376,Smoothie,4.000000,4.0,16.000000,Cash,In-store,2023-08-15
34,TXN_8853997,Smoothie,2.000000,4.0,8.000000,Digital Wallet,Takeaway,2023-10-09
35,TXN_9130559,Sandwich,1.000000,4.0,4.000000,Credit Card,In-store,2023-05-28
37,TXN_1080432,Salad,2.000000,5.0,10.000000,Credit Card,In-store,2023-04-29
38,TXN_2655815,Smoothie,4.000000,4.0,16.000000,Cash,Takeaway,2023-06-08
39,TXN_6688524,Coffee,4.000000,2.0,8.000000,Cash,In-store,2023-06-29
40,TXN_2083138,Smoothie,3.000000,4.0,12.000000,Cash,In-store,2023-04-17
41,TXN_2427584,Sandwich,4.000000,4.0,16.000000,Cash,Takeaway,2023-12-22
42,TXN_6650263,Tea,2.000000,1.5,8.924352,Cash,Takeaway,2023-01-10
43,TXN_9620080,Juice,4.000000,3.0,12.000000,Cash,Takeaway,2023-10-02
44,TXN_1491578,Cookie,2.000000,1.0,2.000000,Cash,In-store,2023-02-23
45,TXN_5455792,Salad,3.000000,5.0,15.000000,Cash,In-store,2023-03-22
46,TXN_8078640,Juice,4.000000,3.0,12.000000,Digital Wallet,In-store,2023-11-03
47,TXN_9499313,Juice,5.000000,3.0,15.000000,Cash,In-store,2023-03-02
48,TXN_8201146,Juice,5.000000,3.0,15.000000,Cash,In-store,2023-06-26
49,TXN_8230936,Cake,3.000000,3.0,9.000000,Cash,In-store,2023-05-02
50,TXN_7742742,Cake,5.000000,3.0,15.000000,Cash,Takeaway,2023-09-05
51,TXN_6342161,Salad,5.000000,5.0,25.000000,Cash,Takeaway,2023-01-08
53,TXN_3363746,Smoothie,3.000000,4.0,12.000000,Credit Card,In-store,2023-11-25
54,TXN_8614868,Smoothie,5.000000,4.0,20.000000,Digital Wallet,Takeaway,2023-12-05
55,TXN_5522862,Cookie,3.029846,1.0,2.000000,Credit Card,Takeaway,2023-03-19
56,TXN_3578141,Cake,5.000000,NaN,15.000000,Cash,Takeaway,2023-06-27
57,TXN_2080895,Cake,3.029846,3.0,3.000000,Digital Wallet,In-store,2023-04-19

In [66]:
df["Transaction Date"]=df["Transaction Date"].replace("ERROR",pd.NA)

In [68]:
df["Transaction Date"].unique()

<StringArray>
['2023-09-08', '2023-05-16', '2023-07-19', '2023-04-27', '2023-06-11',
 '2023-03-31', '2023-10-28', '2023-12-31', '2023-11-07',          nan,
 ...
 '2023-10-06', '2023-11-11', '2023-06-07', '2023-02-13', '2023-07-30',
 '2023-02-17', '2023-05-20', '2023-11-05', '2023-03-27', '2023-07-03']
Length: 367, dtype: str

In [69]:
df["Transaction Date"]=df["Transaction Date"].dropna()

In [70]:
df.head(50)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2.000000,2.0,4.000000,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4.000000,3.0,12.000000,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4.000000,1.0,8.924352,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2.000000,5.0,10.000000,Cash,In-store,2023-04-27
4,TXN_3160411,Coffee,2.000000,2.0,4.000000,Digital Wallet,In-store,2023-06-11
5,TXN_2602893,Smoothie,5.000000,4.0,20.000000,Credit Card,In-store,2023-03-31
7,TXN_6699534,Sandwich,4.000000,4.0,16.000000,Cash,In-store,2023-10-28
9,TXN_2064365,Sandwich,5.000000,4.0,20.000000,Cash,In-store,2023-12-31
10,TXN_2548360,Salad,5.000000,5.0,25.000000,Cash,Takeaway,2023-11-07
11,TXN_3051279,Sandwich,2.000000,4.0,8.000000,Credit Card,Takeaway,NaN
12,TXN_7619095,Sandwich,2.000000,4.0,8.000000,Cash,In-store,2023-05-03
13,TXN_9437049,Cookie,5.000000,1.0,5.000000,Cash,Takeaway,2023-06-01
15,TXN_2847255,Salad,3.000000,5.0,15.000000,Credit Card,In-store,2023-11-15
16,TXN_3765707,Sandwich,1.000000,4.0,4.000000,Cash,In-store,2023-06-10
17,TXN_6769710,Juice,2.000000,3.0,6.000000,Cash,In-store,2023-02-24
18,TXN_8876618,Cake,5.000000,3.0,15.000000,Cash,In-store,2023-03-25
19,TXN_3709394,Juice,4.000000,3.0,12.000000,Cash,Takeaway,2023-01-15
20,TXN_3522028,Smoothie,3.029846,4.0,20.000000,Cash,In-store,2023-04-04
21,TXN_3567645,Smoothie,4.000000,4.0,16.000000,Credit Card,Takeaway,2023-03-30
22,TXN_5132361,Sandwich,3.000000,4.0,12.000000,Digital Wallet,Takeaway,2023-12-01
23,TXN_2616390,Sandwich,2.000000,4.0,8.000000,Cash,In-store,2023-09-18
24,TXN_9400181,Sandwich,5.000000,4.0,20.000000,Cash,In-store,2023-06-03
25,TXN_7958992,Smoothie,3.000000,4.0,8.924352,Cash,In-store,2023-12-13
26,TXN_5183041,Cookie,5.000000,1.0,5.000000,Credit Card,In-store,2023-04-20
27,TXN_5695074,Juice,4.000000,3.0,12.000000,Credit Card,Takeaway,2023-04-10
28,TXN_8467949,Smoothie,5.000000,4.0,20.000000,Credit Card,In-store,2023-03-11
29,TXN_7640952,Cake,4.000000,3.0,12.000000,Digital Wallet,Takeaway,NaN
32,TXN_9677376,Smoothie,4.000000,4.0,16.000000,Cash,In-store,2023-08-15
34,TXN_8853997,Smoothie,2.000000,4.0,8.000000,Digital Wallet,Takeaway,2023-10-09
35,TXN_9130559,Sandwich,1.000000,4.0,4.000000,Credit Card,In-store,2023-05-28
37,TXN_1080432,Salad,2.000000,5.0,10.000000,Credit Card,In-store,2023-04-29
38,TXN_2655815,Smoothie,4.000000,4.0,16.000000,Cash,Takeaway,2023-06-08
39,TXN_6688524,Coffee,4.000000,2.0,8.000000,Cash,In-store,2023-06-29
40,TXN_2083138,Smoothie,3.000000,4.0,12.000000,Cash,In-store,2023-04-17
41,TXN_2427584,Sandwich,4.000000,4.0,16.000000,Cash,Takeaway,2023-12-22
42,TXN_6650263,Tea,2.000000,1.5,8.924352,Cash,Takeaway,2023-01-10
43,TXN_9620080,Juice,4.000000,3.0,12.000000,Cash,Takeaway,2023-10-02
44,TXN_1491578,Cookie,2.000000,1.0,2.000000,Cash,In-store,2023-02-23
45,TXN_5455792,Salad,3.000000,5.0,15.000000,Cash,In-store,2023-03-22
46,TXN_8078640,Juice,4.000000,3.0,12.000000,Digital Wallet,In-store,2023-11-03
47,TXN_9499313,Juice,5.000000,3.0,15.000000,Cash,In-store,2023-03-02
48,TXN_8201146,Juice,5.000000,3.0,15.000000,Cash,In-store,2023-06-26
49,TXN_8230936,Cake,3.000000,3.0,9.000000,Cash,In-store,2023-05-02
50,TXN_7742742,Cake,5.000000,3.0,15.000000,Cash,Takeaway,2023-09-05
51,TXN_6342161,Salad,5.000000,5.0,25.000000,Cash,Takeaway,2023-01-08
53,TXN_3363746,Smoothie,3.000000,4.0,12.000000,Credit Card,In-store,2023-11-25
54,TXN_8614868,Smoothie,5.000000,4.0,20.000000,Digital Wallet,Takeaway,2023-12-05
55,TXN_5522862,Cookie,3.029846,1.0,2.000000,Credit Card,Takeaway,2023-03-19
56,TXN_3578141,Cake,5.000000,NaN,15.000000,Cash,Takeaway,2023-06-27
57,TXN_2080895,Cake,3.029846,3.0,3.000000,Digital Wallet,In-store,2023-04-19

In [78]:
df = df.dropna(subset=["Transaction Date"])

In [79]:
df.head(50)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2.000000,2.0,4.000000,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4.000000,3.0,12.000000,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4.000000,1.0,8.924352,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2.000000,5.0,10.000000,Cash,In-store,2023-04-27
4,TXN_3160411,Coffee,2.000000,2.0,4.000000,Digital Wallet,In-store,2023-06-11
5,TXN_2602893,Smoothie,5.000000,4.0,20.000000,Credit Card,In-store,2023-03-31
7,TXN_6699534,Sandwich,4.000000,4.0,16.000000,Cash,In-store,2023-10-28
9,TXN_2064365,Sandwich,5.000000,4.0,20.000000,Cash,In-store,2023-12-31
10,TXN_2548360,Salad,5.000000,5.0,25.000000,Cash,Takeaway,2023-11-07
12,TXN_7619095,Sandwich,2.000000,4.0,8.000000,Cash,In-store,2023-05-03
13,TXN_9437049,Cookie,5.000000,1.0,5.000000,Cash,Takeaway,2023-06-01
15,TXN_2847255,Salad,3.000000,5.0,15.000000,Credit Card,In-store,2023-11-15
16,TXN_3765707,Sandwich,1.000000,4.0,4.000000,Cash,In-store,2023-06-10
17,TXN_6769710,Juice,2.000000,3.0,6.000000,Cash,In-store,2023-02-24
18,TXN_8876618,Cake,5.000000,3.0,15.000000,Cash,In-store,2023-03-25
19,TXN_3709394,Juice,4.000000,3.0,12.000000,Cash,Takeaway,2023-01-15
20,TXN_3522028,Smoothie,3.029846,4.0,20.000000,Cash,In-store,2023-04-04
21,TXN_3567645,Smoothie,4.000000,4.0,16.000000,Credit Card,Takeaway,2023-03-30
22,TXN_5132361,Sandwich,3.000000,4.0,12.000000,Digital Wallet,Takeaway,2023-12-01
23,TXN_2616390,Sandwich,2.000000,4.0,8.000000,Cash,In-store,2023-09-18
24,TXN_9400181,Sandwich,5.000000,4.0,20.000000,Cash,In-store,2023-06-03
25,TXN_7958992,Smoothie,3.000000,4.0,8.924352,Cash,In-store,2023-12-13
26,TXN_5183041,Cookie,5.000000,1.0,5.000000,Credit Card,In-store,2023-04-20
27,TXN_5695074,Juice,4.000000,3.0,12.000000,Credit Card,Takeaway,2023-04-10
28,TXN_8467949,Smoothie,5.000000,4.0,20.000000,Credit Card,In-store,2023-03-11
32,TXN_9677376,Smoothie,4.000000,4.0,16.000000,Cash,In-store,2023-08-15
34,TXN_8853997,Smoothie,2.000000,4.0,8.000000,Digital Wallet,Takeaway,2023-10-09
35,TXN_9130559,Sandwich,1.000000,4.0,4.000000,Credit Card,In-store,2023-05-28
37,TXN_1080432,Salad,2.000000,5.0,10.000000,Credit Card,In-store,2023-04-29
38,TXN_2655815,Smoothie,4.000000,4.0,16.000000,Cash,Takeaway,2023-06-08
39,TXN_6688524,Coffee,4.000000,2.0,8.000000,Cash,In-store,2023-06-29
40,TXN_2083138,Smoothie,3.000000,4.0,12.000000,Cash,In-store,2023-04-17
41,TXN_2427584,Sandwich,4.000000,4.0,16.000000,Cash,Takeaway,2023-12-22
42,TXN_6650263,Tea,2.000000,1.5,8.924352,Cash,Takeaway,2023-01-10
43,TXN_9620080,Juice,4.000000,3.0,12.000000,Cash,Takeaway,2023-10-02
44,TXN_1491578,Cookie,2.000000,1.0,2.000000,Cash,In-store,2023-02-23
45,TXN_5455792,Salad,3.000000,5.0,15.000000,Cash,In-store,2023-03-22
46,TXN_8078640,Juice,4.000000,3.0,12.000000,Digital Wallet,In-store,2023-11-03
47,TXN_9499313,Juice,5.000000,3.0,15.000000,Cash,In-store,2023-03-02
48,TXN_8201146,Juice,5.000000,3.0,15.000000,Cash,In-store,2023-06-26
49,TXN_8230936,Cake,3.000000,3.0,9.000000,Cash,In-store,2023-05-02
50,TXN_7742742,Cake,5.000000,3.0,15.000000,Cash,Takeaway,2023-09-05
51,TXN_6342161,Salad,5.000000,5.0,25.000000,Cash,Takeaway,2023-01-08
53,TXN_3363746,Smoothie,3.000000,4.0,12.000000,Credit Card,In-store,2023-11-25
54,TXN_8614868,Smoothie,5.000000,4.0,20.000000,Digital Wallet,Takeaway,2023-12-05
55,TXN_5522862,Cookie,3.029846,1.0,2.000000,Credit Card,Takeaway,2023-03-19
56,TXN_3578141,Cake,5.000000,NaN,15.000000,Cash,Takeaway,2023-06-27
57,TXN_2080895,Cake,3.029846,3.0,3.000000,Digital Wallet,In-store,2023-04-19
58,TXN_6421134,Sandwich,4.000000,4.0,16.000000,Cash,Takeaway,2023-11-03
59,TXN_8813311,Juice,5.000000,3.0,15.000000,Cash,In-store,2023-10-07